CREATE TABLE IF NOT EXISTS `provincias` (
  `provincia_id` int(2) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  PRIMARY KEY (`provincia_id`)
) ENGINE=InnoDB AUTO_INCREMENT=24;

INSERT INTO `provincias` (`provincia_id`,`nombre`) VALUES
	(1, 'Buenos Aires'),
  (2, 'Catamarca'),
  (3, 'Chaco'),
  (4, 'Chubut'),
  (5, 'Córdoba'),
  (6, 'Corrientes'),
  (7, 'Entre Ríos'),
  (8, 'Formosa'),
  (9, 'Jujuy'),
  (10, 'La Pampa'),
  (11, 'La Rioja'),
  (12, 'Mendoza'),
  (13, 'Misiones'),
  (14, 'Neuquén'),
  (15, 'Río Negro'),
  (16, 'Salta'),
  (17, 'San Juan'),
  (18, 'San Luis'),
  (19, 'Santa Cruz'),
  (20, 'Santa Fe'),
  (21, 'Santiago del Estero'),
  (22, 'Tierra del Fuego')
  (23, 'Tucumán')
  (24, 'Capital Federal');

CREATE TABLE IF NOT EXISTS `ciudades` (
  `ciudad_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) NOT NULL,
  `provincia_id` int(2) NOT NULL,
  PRIMARY KEY (`ciudad_id`)
) ENGINE=InnoDB AUTO_INCREMENT=47;

INSERT INTO `ciudades` (`ciudad_id`, `nombre` , `provincia_id`) VALUES
	(1, 'Basavilbaso', 7),
  (2, 'Brazo Largo', 7),
  (3, 'Caseros', 7),
  (4, 'Cerrito', 7),
  (5, 'Chajarí', 7),
  (6, 'Colón', 7),
  (7, 'C. del Uruguay', 7),
  (8, 'Concordia', 7),
  (9, 'Crespo', 7),
  (10, 'Diamante', 7),
  (11, 'Federación', 7),
  (12, 'Federal', 7),
  (13, 'Feliciano', 7),
  (14, 'General Ramirez', 7),
  (15, 'Gualeguay', 7),
  (16, 'Gualeguaychú', 7),
  (17, 'Hernandarias', 7),
  (18, 'Ibicuy', 7),
  (19, 'La Paz', 7),
  (20, 'Larroque', 7),
  (21, 'Lib. San Martín', 7),
  (22, 'Liebig', 7),
  (23, 'Lucas González', 7),
  (24, 'María Grande', 7),
  (25, 'Nogoyá', 7),
  (26, 'Oro Verde', 7),
  (27, 'Paraná', 7),
  (28, 'Piedras Blancas', 7),
  (29, 'Pueblo Belgrano', 7),
  (30, 'Pueblo Brugo', 7),
  (31, 'Puerto Alvear', 7),
  (32, 'Puerto Yeruá', 7),
  (33, 'Rosario del Tala', 7),
  (34, 'San José', 7),
  (35, 'San Salvador', 7),
  (36, 'Santa Ana', 7),
  (37, 'Santa Elena', 7),
  (38, 'Ubajay', 7),
  (39, 'Urdinarrain', 7),
  (40, 'Valle María', 7),
  (41, 'Viale', 7),
  (42, 'Victoria', 7),
  (43, 'Villa Elisa', 7),
  (44, 'Villa Paranacito', 7),
  (45, 'Villa Urquiza', 7),
  (46, 'Villaguay', 7);
